name: Publish Docker Image

on:
  schedule:
    - cron: "15 1 * * *"

jobs:
  call-publish-docker-image:
    uses: ./.github/workflows/docker-image.yaml
    secrets:
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

  call-publish-oxide-docker-image:
    needs: call-publish-docker-image
    uses: ./.github/workflows/oxide-docker-image.yaml
    secrets:
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
